### PR TITLE
Python improvements

### PR DESCRIPTION
**Pull request by akx**
The main points are really enumerated in the commit messages :)

I tried to keep changes nonintrusive for the time being – if Python 2 support is dropped (since it's EOL anyway), we could do nicer things with more modern syntax.

### CODE REVIEW

**Comment by gdabah** [comment]
@akx Thanks a lot for your precious contribution Aarni!!!

I didn't know yasm has a python module. I wrote one myself ten years ago and lost it and since then decided it's easier to invoke yasm.exe directly :) slow and ugly, but hey it works.

I will merge everything later on today.

That's curious why you happen to tend distorm?

**Comment by gdabah** [comment]
@akx  How can we make sure that if the windows tests script fails it will affect the Actions?
https://github.com/gdabah/distorm/runs/411214179?check_suite_focus=true

I'm working to fix the actual bug meanwhile.

**Comment by gdabah** [comment]
The problem is that the permissions of the yasm.exe file isn't alright. I believe it might be on purpose because git is afraid to run malicious exes, which makes sense. The question is how to fix the permissions on the GHA. Any idea?
Also fixed some temp file flush issues on windows.

**Comment by akx** [comment]
> I didn't know yasm has a python module. I wrote one myself ten years ago and lost it and since then decided it's easier to invoke yasm.exe directly :) slow and ugly, but hey it works.

It doesn't, but at least the path is now configurable :)

> That's curious why you happen to tend distorm?

I just happened to bump into it and figured I could help out :-)

> How can we make sure that if the windows tests script fails it will affect the Actions?
> https://github.com/gdabah/distorm/runs/411214179?check_suite_focus=true

Huh, weird. I guess Powershell is confused about the `;` syntax and doesn't end up returning the test script's error code to GHA.

**Comment by gdabah** [comment]
Okay cool I will check it out.
I figured it’s the executable after I fixed a windows related problem with
the temporary file.

Thanks again for all your contribution and help!

**Pull request merged**
