### PR TITLE
torture test

### PR DESCRIPTION
**Pull request by sfinktah**
The actual examples/test Makefile was broken (I did fix it), but it seemed easier to put the torture test in examples/linux since the Makefile required bash (but runs on cygwin).

Basically I just happened to be reversing a function (~850 bytes long) that triggered every incompatibility I've seen so far between distorm and yasm/nasm.   I also added a `mov bl, 1` to the end, just to ensure I had fixed that silly bug of mine.

```x86asm
000000014001617c (03) 418bce                   MOV ECX, R14D
000000014001617f (05) 4883241e00               AND QWORD [CR4:RSI+RBX], 0x0
0000000140016184 (05) 4883241f00               AND QWORD [CR4:RDI+RBX], 0x0
```
_(and so forth, and so on)._

    cd examples/linux && make && make torture

If I did the Makefile correctly (a dubious proposition), it will recompile distorm3.a during a regular `make`

And just because I could, I ran the output of distorm3 against that of ndisasm and compared them (after a lot of tweaking, of course).  The differences of note were basically:

1. ndisasm prefers `jmp short` for `eb??` (i don't care for it, personally)
2. ndisasm prefers to qualify 128 byte operations with `movaps oword [rbp+0x47], xmm1` (nasm doesn't care for it, neither do i)
3. ndisasm doesn't put `CR4:` on stuff (i think we already know how nasm and I feel about this :)

```x86asm
*** d.asm       2021-02-05 19:25:21.693251400 +1100
--- n.asm       2021-02-05 19:34:21.338834200 +1100
***************
*** 18 ****
! 140016176  488b1cc8           mov rbx, [cr4:rax+rcx*8]
--- 18 ----
! 140016176  488b1cc8           mov rbx, [rax+rcx*8]
***************
*** 21,22 ****
! 14001617f  4883241e00         and qword [cr4:rsi+rbx], 0x0
! 140016184  4883241f00         and qword [cr4:rdi+rbx], 0x0
--- 21,22 ----
! 14001617f  4883241e00         and qword [rsi+rbx], 0x0
! 140016184  4883241f00         and qword [rdi+rbx], 0x0
***************
*** 27 ****
! 14001619e  4889041e           mov [cr4:rsi+rbx], rax
--- 27 ----
! 14001619e  4889041e           mov [rsi+rbx], rax
***************
*** 29 ****
! 1400161a9  4889041f           mov [cr4:rdi+rbx], rax
--- 29 ----
! 1400161a9  4889041f           mov [rdi+rbx], rax
***************
*** 47 ****
! 1400161f4  eb08               jmp 0x1400161fe
--- 47 ----
! 1400161f4  eb08               jmp short 0x1400161fe
***************
*** 147,148 ****
! 1400163ce  0f1045d7           movups xmm0, [rbp-0x29]
! 1400163d2  0f104de7           movups xmm1, [rbp-0x19]
--- 147,148 ----
! 1400163ce  0f1045d7           movups xmm0, oword [rbp-0x29]
! 1400163d2  0f104de7           movups xmm1, oword [rbp-0x19]
***************
*** 150,155 ****
! 1400163da  0f294537           movaps [rbp+0x37], xmm0
! 1400163de  0f294d47           movaps [rbp+0x47], xmm1
! 1400163e2  0f104517           movups xmm0, [rbp+0x17]
! 1400163e6  0f104d27           movups xmm1, [rbp+0x27]
! 1400163ea  0f2945d7           movaps [rbp-0x29], xmm0
! 1400163ee  0f294de7           movaps [rbp-0x19], xmm1
--- 150,155 ----
! 1400163da  0f294537           movaps oword [rbp+0x37], xmm0
! 1400163de  0f294d47           movaps oword [rbp+0x47], xmm1
! 1400163e2  0f104517           movups xmm0, oword [rbp+0x17]
! 1400163e6  0f104d27           movups xmm1, oword [rbp+0x27]
! 1400163ea  0f2945d7           movaps oword [rbp-0x29], xmm0
! 1400163ee  0f294de7           movaps oword [rbp-0x19], xmm1
```

### CODE REVIEW

**Comment by gdabah** [comment]
@sfinktah I don't see where you compare the torture, so I guess it's done manually?
Anyway, good fix for the makefile, however I can't commit the PR as it's mixing tests with examples and environments.
But if the test is good we can add it to the python one. Although I already added a focused test for the imm problem you found.
You're welcome to double check me obviously!

**Comment by sfinktah** [comment]
@gdabah Ahh, yes -- I agree with your logic.   I have actually written a pure-BASH script (portability) to compare ndisasm and distorm output.

More accurately, I have written a script that renders the output of those two tools identical -- thus allowing identification of any disagreement.

I just have to finish the logic for resolving ndisasm's use of "ptr" sizes such as: 

    and rcx, byte 3

Which I personally find quite annoying as it gives the impression (to assembler novices such as myself) that perhaps the operation only applies to `AL`, rather than it being a (pointless) distinction intended to indicate which variant of `and` a hypothetically retarded assembler should use.

Anyway, such an example is automatically removed by my script using the expedient logic that `byte` is the smallest unit that could house `3`, and is therefore to be removed.

It was the 

    and rcx, byte -3
    
That killed me.   How "big" is -3?  (rhetorical question) and how to teach a BASH script how to work it out.  I think I have a solution, and will upload something when I've confirmed it.  (The fact that ndisasm does actually express it in decimal doesn't help).

**Comment by gdabah** [comment]
@sfinktah honestly I'm not sure why you wrote it in bash, lol. Portability for what? That language tires me. With Python I'm sure it should have been easier. Anyway I don't see how I can merge all this cool stuff in. As it's out of scope for distorm.
Is there any way to trigger a side project of more tests through the GHA?

**Comment by sfinktah** [comment]
Why write it in bash?  For the same reasons people write things in assembler, excluding the the speed advantage.

(Let me know when you come up with that list of reasons, because I have no idea either).

And I didn't really expect you to accept something you couldn't actually fix or tweak if it work, but it was a lot of hard work (like assembly programming) and required some careful planning and clever tricks (again, not unlike assembly programming).



e.g. the code to calculate the minimum size (byte, word, dword, ...) to store a positive or negative number operates directly on hex strings.  Contrast that with my solution for the unsigned int problem that you rewrote, in which I just wrote a loop with a `mask <<= 1`

Most of remaining tricks involve LUTs. there's a LUT of [ byte, word, dword, qword ] that index matches LUTs that contains [ al, ax, eax, rax ] (and all their variants).

It's *cough* highly efficient *cough* BASH script, with all the irony that statement implies.  Though if it were to be recoded in sensible language (and I'm picturing a Python function with a single half-page regular expression), those LUTs will pay off.

Though in all fairness, if I wanted to take the easy route, I could have just tweaked disasm.c to produce ndisasm style output.  That's assuming ndisasm is your desired point of comparison, I just picked it because I found about 9 copies on my system.

If I were to do something in Python, I would would want to use another disassembler with Python bindings.

**Comment by gdabah** [comment]
Actually now I am curious what’s your end goal with this comparison...?

**Comment by sfinktah** [comment]
I believe it was mainly to prove that it could be done in pure BASH.  The idea of using BASH to convert absolute to RIP-relative addressing would be anathema to 99% of reverse engineers.

BTW, do you have any inclination to change `sub rsp, 0x8` to `sub rsp, 8` or does the script need to convert.  I can see how that might increase complexity and reduce speed -- but OTOH you don't output `[RCX*RBC+0x8]`.

**Comment by gdabah** [comment]
@sfinktah it's because they are being output in different functions tbh :(
Anyway, I'm skipping this change, as it's out of scope for distorm directly, though I wish I could add it to the github actions somehow to check sanity...

**Pull request closed without merging**
